#
# PROSE Summarization - 100 examples, 2 max traits
#
parameters:
  base_dir: null
  wandb_mode: disabled
  wandb_ent: null
  logging_level: "info"
  exp_name: ".prose.constrained.human-eval-100-2traits"
  group_name: "plume.summarization.human-eval"
  seed: 1352
  gpt_temperature: 0.01
  qwen_temperature: 0.7
  validation_threshold: 0.5
  num_other_sequences: 0
  num_refinement_steps: 3
  candidate_type: "iterate"
  do_validate_preferences: true
  do_breakdown_preferences_each_iteration: false
  do_breakdown_preferences_after_refinement: true
  include_preferences_in_validate: false
  use_icl: false
  bertscore_model: "microsoft/deberta-xlarge"
  retrieval_underlying_model: "microsoft/deberta-xlarge"
  retrieval_mode: "exact_match"
  encoder_aggregation: "mean_pool"
  retrieval_threshold: null
  user:
    llm_name: "qwen-2_5-7b"
  task:
    name: "summarization"
    framework: "plume"
    datasets: null
    number_of_examples_per_preference_set: 20
    solve_directly: True
  agent:
    llm_name: "qwen-2_5-7b"
    name: "prose"
  constrained_vocabulary: true
  max_traits: 2
